### ISSUE TITLE
problem with two sources with the same name

### ISSUE THREAD

**Issue by surrain** [NothNoth/MIDIRouter#4]
When I run midirouter without a config file, it shows me my available inputs. Two of them have the same name of "KEYBOARD". I can use "KEYBOARD" as a SourceDevice in my config to set one of them as the input, but I can't differentiate between them. One is a microKEY2 Air 49 and the other is a microKEY2 Air 37. I've tried entering the source name different ways, but nothing other than just entering "KEYBOARD" as the SourceDevice works.

I mistakenly posted this issue first on youpy/go-coremidi. They asked that I post it here, but also offered what seems to be an idea of how to address it: https://github.com/youpy/go-coremidi/issues/6#issuecomment-2481136557.

Thanks!

**Comment by NothNoth** [comment]
Hi,

Yes I've already seen that, I will try to see if I can find a workaround

**Comment by NothNoth** [comment]
I just realized that I addressed this issue in last february, now I'm using a manufacturer/Name pair to identify a device.

Are you sure you're using the lastest version?
Can you copy/paste the output of your available in/outs by running ./midirouter with no config?

**Comment by surrain** [comment]
> ./midirouter
Usage: ./midirouter <config file>
MIDI inputs:
   Bus 1
   Bus 2
   Bus 3
   Bus 4
   Bus 5
   Bus 6
   Bus 7
   Bus 8
   Dorico Bus 1
   Dorico Bus 2
   Dorico Bus 3
   Dorico Bus 4
   Dorico Bus 5
   Dorico Bus 6
   Dorico Bus 7
   Dorico Bus 8
   Dorico Bus 9
   Perma49
   Perma37
   Quantum 2626
   KEYBOARD
   KEYBOARD
MIDI outputs:
   Bus 1
   Bus 2
   Bus 3
   Bus 4
   Bus 5
   Bus 6
   Bus 7
   Bus 8
   Dorico Bus 1
   Dorico Bus 2
   Dorico Bus 3
   Dorico Bus 4
   Dorico Bus 5
   Dorico Bus 6
   Dorico Bus 7
   Dorico Bus 8
   Dorico Bus 9
   Perma49
   Perma37
   Quantum 2626
   CTRL
   CTRL

**Comment by surrain** [comment]
https://github.com/NothNoth/MIDIRouter/releases/download/v1.0/midirouter

I believe I'm using that one.

**Comment by NothNoth** [comment]
Oh ok, I thought you were using a home built version.
I've just pushed a v1.1 release with the latest updates, it should fix your issue
Let me know!

**Comment by surrain** [comment]
Thank you. I see the change, but it doesn't help me because it doesn't disambiguate between the two Korg keyboards. It seems to be missing their full names. They are named `microKEY2 Air 49 KEYBOARD` and `microKEY2 Air 37 KEYBOARD` but only the last part of their names is showing.

Here's my new output:
```
> ./midirouter
Usage: ./midirouter <config file>
MIDI inputs:
  Apple Inc./Bus 1
  Apple Inc./Bus 2
  Apple Inc./Bus 3
  Apple Inc./Bus 4
  Apple Inc./Bus 5
  Apple Inc./Bus 6
  Apple Inc./Bus 7
  Apple Inc./Bus 8
  Apple Inc./Dorico Bus 1
  Apple Inc./Dorico Bus 2
  Apple Inc./Dorico Bus 3
  Apple Inc./Dorico Bus 4
  Apple Inc./Dorico Bus 5
  Apple Inc./Dorico Bus 6
  Apple Inc./Dorico Bus 7
  Apple Inc./Dorico Bus 8
  Apple Inc./Dorico Bus 9
  Apple Inc./Perma49
  Apple Inc./Perma37
  PreSonus/Quantum 2626
  KORG INC./KEYBOARD
  KORG INC./KEYBOARD
MIDI outputs:
  Apple Inc./Bus 1
  Apple Inc./Bus 2
  Apple Inc./Bus 3
  Apple Inc./Bus 4
  Apple Inc./Bus 5
  Apple Inc./Bus 6
  Apple Inc./Bus 7
  Apple Inc./Bus 8
  Apple Inc./Dorico Bus 1
  Apple Inc./Dorico Bus 2
  Apple Inc./Dorico Bus 3
  Apple Inc./Dorico Bus 4
  Apple Inc./Dorico Bus 5
  Apple Inc./Dorico Bus 6
  Apple Inc./Dorico Bus 7
  Apple Inc./Dorico Bus 8
  Apple Inc./Dorico Bus 9
  Apple Inc./Perma49
  Apple Inc./Perma37
  PreSonus/Quantum 2626
  KORG INC./CTRL
  KORG INC./CTRL
```

**Comment by NothNoth** [comment]
Ok, I don't think I can address this issue.
Maybe you should look into MacOS midi settings (MIDI Studio) and see if, by changing the name of one of your two keyboards, it reflects on the output of midirouter

**Comment by surrain** [comment]
Thanks. I tried changing the name in MIDI Studio, but it doesn't affect how midirouter sees the device. I'm still seeing two identical KEYBOARD entries.

Can you point me to the place in the code where you're getting this info? Is there any chance you're parsing the providing name in such a way that it's taking only the last portion of the name split somehow by spaces?

**Comment by NothNoth** [comment]
You will find the code which prints the available in/outs in "cmd/midirouter/midirouter.go", but a you will see it's just a :
```
		fmt.Println("MIDI inputs:")
		sources, err := coremidi.AllSources()
		if err != nil {
			panic(err)
		}
		for _, source := range sources {
			fmt.Println("  " + source.Manufacturer() + "/" + source.Name())
		}
```

So I'm just printing whatever the driver (coremidi) gives me. I don't see any other proper way to precisely target a given device.
The main issue here is that you have two device with exactly the same name. How does those appears when using Logic, Protools of anything else?

**Comment by youpy** [comment]
For example, how about looking for a source by device name first, then by manufacturer name and port, as shown below?

```diff
diff --git a/router/setup.go b/router/setup.go
index 738fc09..02c9714 100644
--- a/router/setup.go
+++ b/router/setup.go
@@ -9,21 +9,11 @@ import (
 )
 
 func (relay *MIDIRouter) setupSource() error {
-	split := strings.Split(relay.sourceDevice, "/")
-	if len(split) != 2 {
-		return errors.New("invalid destination format, expected: <manufacturer>/<port> got " + relay.sourceDevice)
-	}
-	manufacturer := split[0]
-	port := split[1]
-
-	//Setup MIDI source
-	valid, err := isValidSourceDevice(manufacturer, port)
+	source, err := findSource(relay.sourceDevice)
 	if err != nil {
 		return err
 	}
-	if valid == false {
-		return errors.New("Invalid MIDI source: " + relay.sourceDevice)
-	}
+
 	relay.srcPort, err = coremidi.NewInputPort(relay.midiClient, relay.sourceDevice+" input port",
 		func(source coremidi.Source, packet coremidi.Packet) {
 			relay.onPacket(source, packet)
@@ -32,23 +22,11 @@ func (relay *MIDIRouter) setupSource() error {
 		return err
 	}
 
-	sources, err := coremidi.AllSources()
+	_, err = relay.srcPort.Connect(source)
 	if err != nil {
-		panic(err)
-	}
-	found := false
-	for _, source := range sources {
-		if source.Manufacturer() == manufacturer && source.Name() == port {
-			relay.srcPort.Connect(source)
-			fmt.Println("Source device: ", source.Entity().Device().Name(), "(", source.Manufacturer(), ")")
-			found = true
-			break
-		}
+		return err
 	}
 
-	if found == false {
-		return errors.New("MIDI source not found.")
-	}
 	return nil
 }
 
@@ -91,18 +69,31 @@ func (relay *MIDIRouter) setupDestination() error {
 	return nil
 }
 
-func isValidSourceDevice(manufactuer string, name string) (bool, error) {
+func findSource(key string) (coremidi.Source, error) {
 	sources, err := coremidi.AllSources()
 	if err != nil {
-		return false, err
+		return coremidi.Source{}, err
 	}
 
 	for _, s := range sources {
-		if s.Manufacturer() == manufactuer && s.Name() == name {
-			return true, nil
+		// first: find by device name
+		if s.Entity().Device().Name() == key {
+			return s, nil
+		}
+
+		// second: find by manufacturer and port
+		split := strings.Split(key, "/")
+		if len(split) == 2 {
+			manufacturer := split[0]
+			port := split[1]
+
+			if s.Manufacturer() == manufacturer && s.Name() == port {
+				return s, nil
+			}
 		}
 	}
-	return false, nil
+
+	return coremidi.Source{}, errors.New("MIDI source not found")
 }
 
 func isValidDestinationDevice(manufactuer string, name string) (bool, error) {
```

**Comment by surrain** [comment]
Thanks. every other MIDI tool I use sees the full names which are longer and different from each other. Only this tool sees only the last word of its name as its full name. On Nov 21, 2024, at 01:44, NothNoth ***@***.***> wrote:﻿
You will find the code which prints the available in/outs in "cmd/midirouter/midirouter.go", but a you will see it's just a :
		fmt.Println("MIDI inputs:")
		sources, err := coremidi.AllSources()
		if err != nil {
			panic(err)
		}
		for _, source := range sources {
			fmt.Println("  " + source.Manufacturer() + "/" + source.Name())
		}

So I'm just printing whatever the driver (coremidi) gives me. I don't see any other proper way to precisely target a given device.
The main issue here is that you have two device with exactly the same name. How does those appears when using Logic, Protools of anything else?

**Comment by NothNoth** [comment]
Hi,

Thank you all for your advices and code snippets, I'll see if I can setup something in the next days

**Comment by NothNoth** [comment]
Hi,

Sorry for the very late update, i've been a bit busy
I've just pushed a new release (v1.2) based on @youpy suggestion.

As usual, just run "./midirouter" with no args to list your available inputs/outputs in order to know what you're supposed to used in your config file.

For sources, I now use a triplet :  Entity().Device().Name() / Manufacturer() / Name()
Sadly, for destinations Entity().Device().Name()  does not exist, thus destination definition is still unchanged.

**Comment by surrain** [comment]
Thanks! It seems like this should work for me now. I'll try it soon. Interesting that the name is cropped after "KEYBOARD" but it seems like that will be inconsequential.

```
> ./midirouter
MIDIRouter v1.2
Usage: ./midirouter <config file>
MIDI inputs:
  IAC Driver/Apple Inc./Perma49
  IAC Driver/Apple Inc./Perma37
  IAC Driver/Apple Inc./Avo Lo
  IAC Driver/Apple Inc./Avo Hi
  IAC Driver/Apple Inc./Bano Lo
  IAC Driver/Apple Inc./Bano Hi
  IAC Driver/Apple Inc./Coco Lo
  IAC Driver/Apple Inc./Coco Hi
  IAC Driver/Apple Inc./Dillo Lo
  IAC Driver/Apple Inc./Dillo Hi
  IAC Driver/Apple Inc./Ego Lo
  IAC Driver/Apple Inc./Ego Hi
  IAC Driver/Apple Inc./Fido Lo
  IAC Driver/Apple Inc./Fido Hi
  IAC Driver/Apple Inc./Dori 1
  IAC Driver/Apple Inc./Dori 2
  IAC Driver/Apple Inc./Dori 3
  Quantum 2626/PreSonus/Quantum 2626
  microKEY2 Air 49/KORG INC./KEYBOARD
  microKEY2 Air 37/KORG INC./KEYBOARD
  //Logic Pro Virtual Out
MIDI outputs:
  Apple Inc./Perma49
  Apple Inc./Perma37
  Apple Inc./Avo Lo
  Apple Inc./Avo Hi
  Apple Inc./Bano Lo
  Apple Inc./Bano Hi
  Apple Inc./Coco Lo
  Apple Inc./Coco Hi
  Apple Inc./Dillo Lo
  Apple Inc./Dillo Hi
  Apple Inc./Ego Lo
  Apple Inc./Ego Hi
  Apple Inc./Fido Lo
  Apple Inc./Fido Hi
  Apple Inc./Dori 1
  Apple Inc./Dori 2
  Apple Inc./Dori 3
  PreSonus/Quantum 2626
  KORG INC./CTRL
  KORG INC./CTRL
  /Logic Pro Virtual In
```
